[new]
title = "V LIVE ─ NEW"
url = "https://www.vlive.tv/home/video/more?pageNo=1&pageSize=50&viewType=recent&lang=ko"
entrySelector = "li.video_list_cont._video"
titleSelector = "a.video_tit"
linkSelector = "a.video_tit"
contentSelector = "div.video_date a.name"
imageSelector = "img"
waitUntil = "networkidle"

[home_new]
title = "V LIVE ─ 홈 ─ NEW"
url = "https://www.vlive.tv/home/new?lang=ko"
entrySelector = "ul.video_list._video li.video_list_cont._video"
titleSelector = "a.video_tit"
linkSelector = "a.video_tit"
contentSelector = "div.video_date a.name"
imageSelector = "a.thumb_area img"
waitUntil = "networkidle"

[home_charts_top3]
title = "V LIVE ─ 홈 ─ CHARTS TOP3"
url = "https://www.vlive.tv/home/chart?sub=VIDEO&period=HOUR_24&country=ALL&lang=ko"
entrySelector = "ul.video_list.video_list-big li.video_list_cont"
titleSelector = "a.video_tit"
linkSelector = "a.video_tit"
contentSelector = "div.video_date a.name"
imageSelector = "a.thumb_area img"
waitUntil = "networkidle"

[home_charts]
title = "V LIVE ─ 홈 ─ CHARTS"
url = "https://www.vlive.tv/home/chart?sub=VIDEO&period=HOUR_24&country=ALL&lang=ko"
entrySelector = "ul.video_list.video_list-landscape li.video_list_cont"
titleSelector = "a.video_tit"
linkSelector = "a.video_tit"
contentSelector = "div.video_date a.name"
imageSelector = "a.thumb_area img"
waitUntil = "networkidle"

[m_home]
title = "V LIVE 모바일 ─ NEW"
url = "https://m.vlive.tv/home&lang=ko"
entrySelector = "div.vcard_box"
titleSelector = "p.tit"
linkSelector = "a.inner_link"
contentSelector = "strong.name"
imageSelector = "div.img_area img"
waitUntil = "networkidle"

[charts]
title = "V LIVE ─ CHARTS"
url = "https://www.vlive.tv/home/chart/more?pageNo=1&pageSize=50&viewType=recent&lang=ko"
entrySelector = "li.video_list_cont"
titleSelector = "a.video_tit"
linkSelector = "a.video_tit"
contentSelector = "div.video_date a.name"
imageSelector = "img"
waitUntil = "networkidle"

[m_charts_top3]
title = "V LIVE 모바일 ─ CHARTS "
url = "https://m.vlive.tv/chart?sub=VIDEO&period=HOUR_24&country=ALL&lang=ko"
entrySelector = "div.inner_wrap._video_chart_list div.vcard_box"
titleSelector = "p.tit"
linkSelector = "a.inner_link"
contentSelector = "strong.name"
imageSelector = "div.img_area img"
waitUntil = "networkidle"

[m_charts]
title = "V LIVE 모바일 ─ CHARTS"
url = "https://m.vlive.tv/chart?sub=VIDEO&period=HOUR_24&country=ALL&lang=ko"
entrySelector = "div.inner_wrap._video_chart_list div.vthumb_card"
titleSelector = "p.tit"
linkSelector = "a.inner_link"
contentSelector = "span.channel"
imageSelector = "div.vthumb_img img"
waitUntil = "networkidle"

[upcoming]
title = "V LIVE ─ 일정표"
url = "https://www.vlive.tv/upcoming?lang=ko"
entrySelector = "ul.upcoming_list li"
titleSelector = "em.title a._title"
linkSelector = "em.title a._title"
contentSelector = "span.time"
imageSelector = "a.thumb._videoThumb img"
waitForSelector = "ul.upcoming_list li"

[m_upcoming]
title = "V LIVE 모바일 ─ 일정표"
url = "https://m.vlive.tv/upcoming?lang=ko"
entrySelector = "div.vthumb_box.upcoming"
titleSelector = "div.vthumb_info p.tit"
linkSelector = "a.inner_link"
contentSelector = "div.date_area"
imageSelector = "div.vthumb_img img"
waitUntil = "networkidle"
