[vlive]
title = "V LIVE ─ NEW"
url = "https://www.vlive.tv/home/video/more?pageNo=1&pageSize=50&viewType=recent"
entrySelector = "li.video_list_cont._video"
titleSelector = "a.video_tit"
linkSelector = "a.video_tit"
contentSelector = "div.video_date a.name"
imageSelector = "img"
waitUntil = "networkidle"

[vlive_upcoming]
title = "V LIVE ─ 일정표"
url = "https://www.vlive.tv/upcoming?lang=ko"
entrySelector = "div.upcoming_wrap div.upcoming_area ul.upcoming_list li:not(.replay):not(.on)"
titleSelector = "em.title a._title"
linkSelector = "em.title a._title"
contentSelector = "span.time"
imageSelector = "a.thumb._videoThumb img"
waitForSelector = "ul.upcoming_list li"

[m_vlive_upcoming]
title = "V LIVE 모바일 ─ 일정표"
url = "https://m.vlive.tv/upcoming?lang=ko"
entrySelector = "div.vthumb_box.upcoming"
titleSelector = "div.vthumb_info p.tit"
linkSelector = "a.inner_link"
contentSelector = "div.date_area"
imageSelector = "div.vthumb_img img"
waitUntil = "networkidle"
